require:
  - rubocop-capybara
  - rubocop-packaging
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.3.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - tmp/**/*
    - vendor/**/*
    - temp_app/**/*

Layout/LineLength:
  Max: 200
